<?php

use Illuminate\Database\Seeder;

class PlayerTableSeeder extends Seeder {

	/**
	 * Auto generated seed file
	 *
	 * @return void
	 */
	public function run()
	{
		\DB::table('player')->delete();
        
		\DB::table('player')->insert(array (
			0 => 
			array (
				'id' => 1,
				'first_name' => 'lele',
				'last_name' => 'lelelel',
				'alias' => 'Caio',
				'role' => '',
				'DOB' => NULL,
				'age' => 0,
				'first_event' => '',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
				'hometown' => NULL,
				'country' => NULL,
				'photo_url' => NULL,
				'twitter_widget' => NULL,
			),
			1 => 
			array (
				'id' => 2,
				'first_name' => 'lele',
				'last_name' => 'lelelel',
				'alias' => 'Carlao',
				'role' => '',
				'DOB' => NULL,
				'age' => 0,
				'first_event' => '',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
				'hometown' => NULL,
				'country' => NULL,
				'photo_url' => NULL,
				'twitter_widget' => NULL,
			),
			2 => 
			array (
				'id' => 3,
				'first_name' => 'lele',
				'last_name' => 'lelelel',
				'alias' => 'Le',
				'role' => '',
				'DOB' => NULL,
				'age' => 0,
				'first_event' => '',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
				'hometown' => NULL,
				'country' => NULL,
				'photo_url' => NULL,
				'twitter_widget' => NULL,
			),
			3 => 
			array (
				'id' => 4,
				'first_name' => 'lele',
				'last_name' => 'lelelel',
				'alias' => 'Hx',
				'role' => '',
				'DOB' => NULL,
				'age' => 0,
				'first_event' => '',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
				'hometown' => NULL,
				'country' => NULL,
				'photo_url' => NULL,
				'twitter_widget' => NULL,
			),
			4 => 
			array (
				'id' => 5,
				'first_name' => 'lele',
				'last_name' => 'lelelel',
				'alias' => 'Sharq',
				'role' => '',
				'DOB' => NULL,
				'age' => 0,
				'first_event' => '',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
				'hometown' => NULL,
				'country' => NULL,
				'photo_url' => NULL,
				'twitter_widget' => NULL,
			),
			5 => 
			array (
				'id' => 6,
				'first_name' => 'lele',
				'last_name' => 'lelelel',
				'alias' => 'eMegicz',
				'role' => '',
				'DOB' => NULL,
				'age' => 0,
				'first_event' => '',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
				'hometown' => NULL,
				'country' => NULL,
				'photo_url' => NULL,
				'twitter_widget' => NULL,
			),
			6 => 
			array (
				'id' => 7,
				'first_name' => 'lele',
				'last_name' => 'lelelel',
				'alias' => 'Guigs',
				'role' => '',
				'DOB' => NULL,
				'age' => 0,
				'first_event' => '',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
				'hometown' => NULL,
				'country' => NULL,
				'photo_url' => NULL,
				'twitter_widget' => NULL,
			),
			7 => 
			array (
				'id' => 8,
				'first_name' => 'lele',
				'last_name' => 'lelelel',
				'alias' => 'RyeK',
				'role' => '',
				'DOB' => NULL,
				'age' => 0,
				'first_event' => '',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
				'hometown' => NULL,
				'country' => NULL,
				'photo_url' => NULL,
				'twitter_widget' => NULL,
			),
			8 => 
			array (
				'id' => 9,
				'first_name' => 'lele',
				'last_name' => 'lelelel',
				'alias' => 'Theuss',
				'role' => '',
				'DOB' => NULL,
				'age' => 0,
				'first_event' => '',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
				'hometown' => NULL,
				'country' => NULL,
				'photo_url' => NULL,
				'twitter_widget' => NULL,
			),
			9 => 
			array (
				'id' => 10,
				'first_name' => 'lele',
				'last_name' => 'lelelel',
				'alias' => 'LGnDz',
				'role' => '',
				'DOB' => NULL,
				'age' => 0,
				'first_event' => '',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
				'hometown' => NULL,
				'country' => NULL,
				'photo_url' => NULL,
				'twitter_widget' => NULL,
			),
			10 => 
			array (
				'id' => 11,
				'first_name' => 'lele',
				'last_name' => 'lelelel',
				'alias' => 'Lopes',
				'role' => '',
				'DOB' => NULL,
				'age' => 0,
				'first_event' => '',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
				'hometown' => NULL,
				'country' => NULL,
				'photo_url' => NULL,
				'twitter_widget' => NULL,
			),
			11 => 
			array (
				'id' => 12,
				'first_name' => 'lele',
				'last_name' => 'lelelel',
				'alias' => 'RapidBigThug',
				'role' => '',
				'DOB' => NULL,
				'age' => 0,
				'first_event' => '',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
				'hometown' => NULL,
				'country' => NULL,
				'photo_url' => NULL,
				'twitter_widget' => NULL,
			),
			12 => 
			array (
				'id' => 13,
				'first_name' => 'lele',
				'last_name' => 'lelelel',
				'alias' => 'Batuta',
				'role' => '',
				'DOB' => NULL,
				'age' => 0,
				'first_event' => '',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
				'hometown' => NULL,
				'country' => NULL,
				'photo_url' => NULL,
				'twitter_widget' => NULL,
			),
			13 => 
			array (
				'id' => 14,
				'first_name' => 'lele',
				'last_name' => 'lelelel',
				'alias' => 'FKiNg',
				'role' => '',
				'DOB' => NULL,
				'age' => 0,
				'first_event' => '',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
				'hometown' => NULL,
				'country' => NULL,
				'photo_url' => NULL,
				'twitter_widget' => NULL,
			),
			14 => 
			array (
				'id' => 15,
				'first_name' => 'lele',
				'last_name' => 'lelelel',
				'alias' => 'eRoDy',
				'role' => '',
				'DOB' => NULL,
				'age' => 0,
				'first_event' => '',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
				'hometown' => NULL,
				'country' => NULL,
				'photo_url' => NULL,
				'twitter_widget' => NULL,
			),
			15 => 
			array (
				'id' => 16,
				'first_name' => 'lele',
				'last_name' => 'lelelel',
				'alias' => 'DJNAY',
				'role' => '',
				'DOB' => NULL,
				'age' => 0,
				'first_event' => '',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
				'hometown' => NULL,
				'country' => NULL,
				'photo_url' => NULL,
				'twitter_widget' => NULL,
			),
			16 => 
			array (
				'id' => 18,
				'first_name' => 'lele',
				'last_name' => 'lelelel',
				'alias' => 'Nikko',
				'role' => '',
				'DOB' => NULL,
				'age' => 0,
				'first_event' => '',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
				'hometown' => NULL,
				'country' => NULL,
				'photo_url' => NULL,
				'twitter_widget' => NULL,
			),
			17 => 
			array (
				'id' => 19,
				'first_name' => 'lele',
				'last_name' => 'lelelel',
				'alias' => 'ForTunaTo',
				'role' => '',
				'DOB' => NULL,
				'age' => 0,
				'first_event' => '',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
				'hometown' => NULL,
				'country' => NULL,
				'photo_url' => NULL,
				'twitter_widget' => NULL,
			),
			18 => 
			array (
				'id' => 20,
				'first_name' => 'lele',
				'last_name' => 'lelelel',
				'alias' => 'iRapp',
				'role' => '',
				'DOB' => NULL,
				'age' => 0,
				'first_event' => '',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
				'hometown' => NULL,
				'country' => NULL,
				'photo_url' => NULL,
				'twitter_widget' => NULL,
			),
			19 => 
			array (
				'id' => 21,
				'first_name' => 'lele',
				'last_name' => 'lelelel',
				'alias' => 'STAL1ZY',
				'role' => '',
				'DOB' => NULL,
				'age' => 0,
				'first_event' => '',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
				'hometown' => NULL,
				'country' => NULL,
				'photo_url' => NULL,
				'twitter_widget' => NULL,
			),
			20 => 
			array (
				'id' => 22,
				'first_name' => 'lele',
				'last_name' => 'lelelel',
				'alias' => 'Rafa',
				'role' => '',
				'DOB' => NULL,
				'age' => 0,
				'first_event' => '',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
				'hometown' => NULL,
				'country' => NULL,
				'photo_url' => NULL,
				'twitter_widget' => NULL,
			),
			21 => 
			array (
				'id' => 23,
				'first_name' => 'lele',
				'last_name' => 'lelelel',
				'alias' => 'RxcK',
				'role' => '',
				'DOB' => NULL,
				'age' => 0,
				'first_event' => '',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
				'hometown' => NULL,
				'country' => NULL,
				'photo_url' => NULL,
				'twitter_widget' => NULL,
			),
			22 => 
			array (
				'id' => 24,
				'first_name' => 'lele',
				'last_name' => 'lelelel',
				'alias' => 'VrTChamp',
				'role' => '',
				'DOB' => NULL,
				'age' => 0,
				'first_event' => '',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
				'hometown' => NULL,
				'country' => NULL,
				'photo_url' => NULL,
				'twitter_widget' => NULL,
			),
			23 => 
			array (
				'id' => 25,
				'first_name' => 'lele',
				'last_name' => 'lelelel',
				'alias' => 'CocoLander',
				'role' => '',
				'DOB' => NULL,
				'age' => 0,
				'first_event' => '',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
				'hometown' => NULL,
				'country' => NULL,
				'photo_url' => NULL,
				'twitter_widget' => NULL,
			),
		));
	}

}
