<?php

use Illuminate\Database\Seeder;

class SndTableSeeder extends Seeder {

	/**
	 * Auto generated seed file
	 *
	 * @return void
	 */
	public function run()
	{
		\DB::table('snd')->delete();
        
		\DB::table('snd')->insert(array (
			0 => 
			array (
				'id' => 1,
				'game_id' => 2,
				'team_a_score' => 6,
				'team_b_score' => 4,
				'a_offense_wins' => 0,
				'b_offense_wins' => 0,
				'a_defense_wins' => 0,
				'b_defense_wins' => 0,
				'a_plant_a' => NULL,
				'a_plant_b' => NULL,
				'a_plant_a_win' => NULL,
				'a_plant_b_win' => NULL,
				'b_plant_a' => NULL,
				'b_plant_b' => NULL,
				'b_plant_a_win' => NULL,
				'b_plant_b_win' => NULL,
				'team_a_host' => 0,
				'team_b_host' => 0,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
				'game_time' => 600,
				'a_victory' => 1,
			),
			1 => 
			array (
				'id' => 2,
				'game_id' => 5,
				'team_a_score' => 2,
				'team_b_score' => 6,
				'a_offense_wins' => 0,
				'b_offense_wins' => 0,
				'a_defense_wins' => 0,
				'b_defense_wins' => 0,
				'a_plant_a' => NULL,
				'a_plant_b' => NULL,
				'a_plant_a_win' => NULL,
				'a_plant_b_win' => NULL,
				'b_plant_a' => NULL,
				'b_plant_b' => NULL,
				'b_plant_a_win' => NULL,
				'b_plant_b_win' => NULL,
				'team_a_host' => 0,
				'team_b_host' => 0,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
				'game_time' => 600,
				'a_victory' => 0,
			),
			2 => 
			array (
				'id' => 3,
				'game_id' => 9,
				'team_a_score' => 6,
				'team_b_score' => 5,
				'a_offense_wins' => 0,
				'b_offense_wins' => 0,
				'a_defense_wins' => 0,
				'b_defense_wins' => 0,
				'a_plant_a' => NULL,
				'a_plant_b' => NULL,
				'a_plant_a_win' => NULL,
				'a_plant_b_win' => NULL,
				'b_plant_a' => NULL,
				'b_plant_b' => NULL,
				'b_plant_a_win' => NULL,
				'b_plant_b_win' => NULL,
				'team_a_host' => 0,
				'team_b_host' => 0,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
				'game_time' => 597,
				'a_victory' => 1,
			),
			3 => 
			array (
				'id' => 4,
				'game_id' => 12,
				'team_a_score' => 5,
				'team_b_score' => 6,
				'a_offense_wins' => 0,
				'b_offense_wins' => 0,
				'a_defense_wins' => 0,
				'b_defense_wins' => 0,
				'a_plant_a' => NULL,
				'a_plant_b' => NULL,
				'a_plant_a_win' => NULL,
				'a_plant_b_win' => NULL,
				'b_plant_a' => NULL,
				'b_plant_b' => NULL,
				'b_plant_a_win' => NULL,
				'b_plant_b_win' => NULL,
				'team_a_host' => 0,
				'team_b_host' => 0,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
				'game_time' => 600,
				'a_victory' => 0,
			),
			4 => 
			array (
				'id' => 5,
				'game_id' => 14,
				'team_a_score' => 6,
				'team_b_score' => 5,
				'a_offense_wins' => 0,
				'b_offense_wins' => 0,
				'a_defense_wins' => 0,
				'b_defense_wins' => 0,
				'a_plant_a' => NULL,
				'a_plant_b' => NULL,
				'a_plant_a_win' => NULL,
				'a_plant_b_win' => NULL,
				'b_plant_a' => NULL,
				'b_plant_b' => NULL,
				'b_plant_a_win' => NULL,
				'b_plant_b_win' => NULL,
				'team_a_host' => 0,
				'team_b_host' => 0,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
				'game_time' => 619,
				'a_victory' => 1,
			),
			5 => 
			array (
				'id' => 6,
				'game_id' => 17,
				'team_a_score' => 6,
				'team_b_score' => 5,
				'a_offense_wins' => 0,
				'b_offense_wins' => 0,
				'a_defense_wins' => 0,
				'b_defense_wins' => 0,
				'a_plant_a' => NULL,
				'a_plant_b' => NULL,
				'a_plant_a_win' => NULL,
				'a_plant_b_win' => NULL,
				'b_plant_a' => NULL,
				'b_plant_b' => NULL,
				'b_plant_a_win' => NULL,
				'b_plant_b_win' => NULL,
				'team_a_host' => 0,
				'team_b_host' => 0,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
				'game_time' => 594,
				'a_victory' => 1,
			),
			6 => 
			array (
				'id' => 7,
				'game_id' => 20,
				'team_a_score' => 6,
				'team_b_score' => 4,
				'a_offense_wins' => 0,
				'b_offense_wins' => 0,
				'a_defense_wins' => 0,
				'b_defense_wins' => 0,
				'a_plant_a' => NULL,
				'a_plant_b' => NULL,
				'a_plant_a_win' => NULL,
				'a_plant_b_win' => NULL,
				'b_plant_a' => NULL,
				'b_plant_b' => NULL,
				'b_plant_a_win' => NULL,
				'b_plant_b_win' => NULL,
				'team_a_host' => 0,
				'team_b_host' => 0,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
				'game_time' => 603,
				'a_victory' => 1,
			),
			7 => 
			array (
				'id' => 8,
				'game_id' => 23,
				'team_a_score' => 6,
				'team_b_score' => 5,
				'a_offense_wins' => 0,
				'b_offense_wins' => 0,
				'a_defense_wins' => 0,
				'b_defense_wins' => 0,
				'a_plant_a' => NULL,
				'a_plant_b' => NULL,
				'a_plant_a_win' => NULL,
				'a_plant_b_win' => NULL,
				'b_plant_a' => NULL,
				'b_plant_b' => NULL,
				'b_plant_a_win' => NULL,
				'b_plant_b_win' => NULL,
				'team_a_host' => 0,
				'team_b_host' => 0,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
				'game_time' => 612,
				'a_victory' => 1,
			),
			8 => 
			array (
				'id' => 9,
				'game_id' => 27,
				'team_a_score' => 3,
				'team_b_score' => 6,
				'a_offense_wins' => 0,
				'b_offense_wins' => 0,
				'a_defense_wins' => 0,
				'b_defense_wins' => 0,
				'a_plant_a' => NULL,
				'a_plant_b' => NULL,
				'a_plant_a_win' => NULL,
				'a_plant_b_win' => NULL,
				'b_plant_a' => NULL,
				'b_plant_b' => NULL,
				'b_plant_a_win' => NULL,
				'b_plant_b_win' => NULL,
				'team_a_host' => 0,
				'team_b_host' => 0,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
				'game_time' => 551,
				'a_victory' => 0,
			),
			9 => 
			array (
				'id' => 10,
				'game_id' => 30,
				'team_a_score' => 0,
				'team_b_score' => 6,
				'a_offense_wins' => 0,
				'b_offense_wins' => 0,
				'a_defense_wins' => 0,
				'b_defense_wins' => 0,
				'a_plant_a' => NULL,
				'a_plant_b' => NULL,
				'a_plant_a_win' => NULL,
				'a_plant_b_win' => NULL,
				'b_plant_a' => NULL,
				'b_plant_b' => NULL,
				'b_plant_a_win' => NULL,
				'b_plant_b_win' => NULL,
				'team_a_host' => 0,
				'team_b_host' => 0,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
				'game_time' => 306,
				'a_victory' => 0,
			),
		));
	}

}
